When you have setup a connection to the data source in your project, you can drag and drop the connection information into the cell below from the "Find and Add Data" palette to the right:
When using generated python dictionary later in the notebook, check you are using the correct reference (eg. credentials_1)

In [1]:
# The code was removed by DSX for sharing.

In [2]:
from ingest import Connectors
from pyspark.sql import SQLContext
sqlContext = SQLContext(sc)

dashDBloadOptions = { Connectors.DASHDB.HOST              : credentials_1['host'],
                      Connectors.DASHDB.DATABASE          : credentials_1['db'],
                      Connectors.DASHDB.USERNAME          : credentials_1['username'],
                      Connectors.DASHDB.PASSWORD          : credentials_1['password'],
                      Connectors.DASHDB.SOURCE_TABLE_NAME : 'GOSALESDW.EMP_EXPENSE_FACT'}

dashdbDF = sqlContext.read.format("com.ibm.spark.discover").options(**dashDBloadOptions).load()
dashdbDF.printSchema()
dashdbDF.show()

root
 |-- DAY_KEY: integer (nullable = false)
 |-- ORGANIZATION_KEY: integer (nullable = false)
 |-- POSITION_KEY: integer (nullable = false)
 |-- EMPLOYEE_KEY: integer (nullable = false)
 |-- EXPENSE_TYPE_KEY: integer (nullable = false)
 |-- ACCOUNT_KEY: integer (nullable = false)
 |-- EXPENSE_UNIT_QUANTITY: double (nullable = true)
 |-- EXPENSE_TOTAL: decimal(19,2) (nullable = true)

+--------+----------------+------------+------------+----------------+-----------+---------------------+-------------+
| DAY_KEY|ORGANIZATION_KEY|POSITION_KEY|EMPLOYEE_KEY|EXPENSE_TYPE_KEY|ACCOUNT_KEY|EXPENSE_UNIT_QUANTITY|EXPENSE_TOTAL|
+--------+----------------+------------+------------+----------------+-----------+---------------------+-------------+
|20120731|           11170|       43639|        4053|            2124|       8056|                 0.03|       483.97|
|20120731|           11170|       43639|        4053|            2130|       8050|                0.005|     11574.80|
|20120731|           11170|       43639|        4053|            2131|       8049|               116.25|      3364.01|
|20120831|           11170|       43639|        4053|            2104|       8050|                  7.5|       198.16|
|20120831|           11170|       43639|        4053|            2120|       8052|                 0.08|       872.64|
|20120831|           11170|       43639|        4053|            2122|       8054|                 0.11|      1199.88|
|20120831|           11170|       43639|        4053|            2124|       8056|                 0.03|       327.24|
|20120831|           11170|       43639|        4053|            2130|       8050|                0.005|      6350.28|
|20120831|           11170|       43639|        4053|            2131|       8049|                165.0|      4359.53|
|20120930|           11170|       43639|        4053|            2120|       8052|                 0.08|      1205.09|
|20120930|           11170|       43639|        4053|            2122|       8054|                 0.11|      1657.00|
|20120930|           11170|       43639|        4053|            2124|       8056|                 0.03|       451.91|
|20120930|           11170|       43639|        4053|            2130|       8050|                0.005|     10505.99|
|20120930|           11170|       43639|        4053|            2131|       8049|                157.5|      4557.69|
|20121031|           11170|       43639|        4053|            2103|       8050|                 37.5|      1035.84|
|20121031|           11170|       43639|        4053|            2120|       8052|                 0.08|       868.99|
|20121031|           11170|       43639|        4053|            2122|       8054|                 0.11|      1194.86|
|20121031|           11170|       43639|        4053|            2124|       8056|                 0.03|       325.87|
|20121031|           11170|       43639|        4053|            2130|       8050|                0.005|      6304.70|
|20121031|           11170|       43639|        4053|            2131|       8049|                127.5|      3521.85|
+--------+----------------+------------+------------+----------------+-----------+---------------------+-------------+
only showing top 20 rows

In [3]:
# Convert spark dataframe to pandas
import pandas as pd
dashdbDF.toPandas()

,DAY_KEY,ORGANIZATION_KEY,POSITION_KEY,EMPLOYEE_KEY,EXPENSE_TYPE_KEY,ACCOUNT_KEY,EXPENSE_UNIT_QUANTITY,EXPENSE_TOTAL
0,20120331,11179,43615,4636,2124,8056,0.0300,92.31
1,20120331,11179,43615,4636,2131,8049,172.5000,3076.92
2,20120430,11179,43615,4636,2120,8052,0.0800,246.15
3,20120430,11179,43615,4636,2122,8054,0.1100,338.46
4,20120430,11179,43615,4636,2124,8056,0.0300,92.31
5,20120430,11179,43615,4636,2131,8049,150.0000,3076.92
6,20120531,11179,43615,4636,2103,8050,45.0000,802.68
7,20120531,11179,43615,4636,2120,8052,0.0800,246.15
8,20120531,11179,43615,4636,2122,8054,0.1100,338.46
9,20120531,11179,43615,4636,2124,8056,0.0300,92.31
10,20120531,11179,43615,4636,2131,8049,127.5000,2274.24
11,20120630,11179,43615,4636,2102,8051,0.0401,1704.47
12,20120630,11179,43615,4636,2120,8052,0.0800,382.51
13,20120630,11179,43615,4636,2122,8054,0.1100,525.95
14,20120630,11179,43615,4636,2124,8056,0.0300,143.44
15,20120630,11179,43615,4636,2131,8049,165.0000,3076.92
16,20120731,11179,43615,4636,2120,8052,0.0800,246.15
17,20120731,11179,43615,4636,2122,8054,0.1100,338.46
18,20120731,11179,43615,4636,2124,8056,0.0300,92.31
19,20120731,11179,43615,4636,2131,8049,157.5000,3076.92
20,20120831,11179,43615,4636,2120,8052,0.0800,246.15
21,20120831,11179,43615,4636,2122,8054,0.1100,338.46
22,20120831,11179,43615,4636,2124,8056,0.0300,92.31
23,20120831,11179,43615,4636,2131,8049,172.5000,3076.92
24,20120930,11179,43615,4636,2120,8052,0.0800,246.15
25,20120930,11179,43615,4636,2122,8054,0.1100,338.46
26,20120930,11179,43615,4636,2124,8056,0.0300,92.31
27,20120930,11179,43615,4636,2131,8049,157.5000,3076.92
28,20121031,11179,43615,4636,2103,8050,37.5000,699.30
29,20121031,11179,43615,4636,2120,8052,0.0800,246.15
...,...,...,...,...,...,...,...,...
127954,20111031,11199,43612,4505,2124,8056,0.0300,145.57
127955,20111031,11199,43612,4505,2131,8049,127.5000,3845.00
127956,20111130,11199,43612,4505,2120,8052,0.0800,423.08
127957,20111130,11199,43612,4505,2122,8054,0.1100,581.73
127958,20111130,11199,43612,4505,2124,8056,0.0300,158.65
127959,20111130,11199,43612,4505,2131,8049,165.0000,5288.46
127960,20111231,11199,43612,4505,2103,8050,112.5000,3605.77
127961,20111231,11199,43612,4505,2120,8052,0.0800,423.08
127962,20111231,11199,43612,4505,2122,8054,0.1100,581.73
127963,20111231,11199,43612,4505,2124,8056,0.0300,158.65
127964,20111231,11199,43612,4505,2131,8049,52.5000,1682.69
127965,20120131,11199,43612,4505,2120,8052,0.0800,423.08
127966,20120131,11199,43612,4505,2122,8054,0.1100,581.73
127967,20120131,11199,43612,4505,2124,8056,0.0300,158.65
127968,20120131,11199,43612,4505,2131,8049,165.0000,5288.46
127969,20120228,11199,43612,4505,2120,8052,0.0800,423.08
127970,20120228,11199,43612,4505,2122,8054,0.1100,581.73
127971,20120228,11199,43612,4505,2124,8056,0.0300,158.65
127972,20120228,11199,43612,4505,2131,8049,150.0000,5288.46
127973,20120331,11199,43612,4505,2103,8050,37.5000,1149.67
127974,20120331,11199,43612,4505,2104,8050,11.2500,344.90
127975,20120331,11199,43612,4505,2120,8052,0.0800,423.08
127976,20120331,11199,43612,4505,2122,8054,0.1100,581.73
127977,20120331,11199,43612,4505,2124,8056,0.0300,158.65
127978,20120331,11199,43612,4505,2131,8049,123.7500,3793.89
127979,20120430,11199,43612,4505,2104,8050,15.0000,528.85
127980,20120430,11199,43612,4505,2120,8052,0.0800,423.08
127981,20120430,11199,43612,4505,2122,8054,0.1100,581.73
127982,20120430,11199,43612,4505,2124,8056,0.0300,158.65
127983,20120430,11199,43612,4505,2131,8049,135.0000,4759.61